sudo: true
language: python
python:
 - "3.4"
env:
  global:
  matrix:
   - DJANGO=Django==1.7.7
install:
 - sudo apt-get update
 - sudo apt-get install -y libav-tools libmp3lame0 libavcodec-extra-*
 - pip install -r requirements.txt
 - pip install $DJANGO
 - pip install coverage
 - pip install flake8
 - python manage.py makemigrations
branches:
 only:
  - master
script:
 - rm __init__.py
 - coverage run --source=臺灣言語資料庫 manage.py test
 - flake8
matrix:
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
